{"now": "2016/02/28 11:55:43 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689343.72409, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:55:45 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689345.113306, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:55:45 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689345.288069, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:55:45 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689345.706496, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:55:46 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689346.298956, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:55:47 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689347.453535, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:55:59 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689359.69067, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:00 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689360.568012, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:01 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689361.790905, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:06 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689366.063089, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:06 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689366.796732, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:10 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689370.233026, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:12 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689372.114582, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:56:15 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689375.205484, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:15 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689435.43424, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:16 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689436.182405, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:16 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689436.777989, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:17 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689437.506234, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:17 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689437.863464, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:18 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689438.370713, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:18 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689438.877166, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:18 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689438.9217, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:18 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689438.933208, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:19 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689439.432228, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:19 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689439.43713, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:19 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689439.436523, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
{"now": "2016/02/28 11:57:19 -0800", "version": "4.1.10", "plugin": "xcode/7.2.1-9548.1 xcode-wakatime/2.0.9", "time": 1456689439.840064, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"/Users/shan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin/Contents/Resources/wakatime-master/wakatime/stats.py\", line 192, in get_file_contents\n    text = fh.read(512000)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 674, in read\n    return self.reader.read(size)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py\", line 480, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte\n"}
